name: Integrate
on:
  workflow_run:
    workflows:
      - build-test
    types:
      - completed
jobs:
  integrate:
    name: integrate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Run integration action
        id: integrate
        uses: ./
        with:
          branch-pattern: "^for_(?<base>[-a-zA-Z/._0-9]+)_(?<identifier>[a-zA-Z]+)$"
          create-base-if-missing: true
          delete-source: true
          abort-integration-if-different-commits-on-origin: true
      - name: Outputs
        env:
          INTEGRATION_TARGET: ${{ steps.integrate.outputs.integration-target }}
          DID_INTEGRATE: ${{ steps.integrate.outputs.did-integrate }}
          ABORTION_REASON: ${{ steps.integrate.outputs.abortion-reason }}
          DELETED_SOURCE: ${{ steps.integrate.outputs.deleted-source }}
          CREATED_BASE: ${{ steps.integrate.outputs.created-base }}
        shell: bash
        run: |
            echo "Outputs:"
            echo "integration-target: ${INTEGRATION_TARGET}"
            echo "did-integrate: ${DID_INTEGRATE}"
            echo "abortion-reason: ${ABORTION_REASON}"
            echo "deleted-source: ${DELETED_SOURCE}"
            echo "created-base: ${CREATED_BASE}"
